// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8nShybfZ9kcpCOW5la6igyPxCq-Dkj1E',
    appId: '1:820548187793:web:14a48a9ac39bbcece43130',
    messagingSenderId: '820548187793',
    projectId: 'titassportswear',
    authDomain: 'titassportswear.firebaseapp.com',
    storageBucket: 'titassportswear.appspot.com',
    measurementId: 'G-60L686SN0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7MfqSfdn6V6O6noKHh0bj5V1ytDuRC3o',
    appId: '1:820548187793:android:9d6b6b1cbce70e84e43130',
    messagingSenderId: '820548187793',
    projectId: 'titassportswear',
    storageBucket: 'titassportswear.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ_CvRDfHylh_kcYL_x_ymYrzQ93RgwLc',
    appId: '1:820548187793:ios:a570a7ca17b753dee43130',
    messagingSenderId: '820548187793',
    projectId: 'titassportswear',
    storageBucket: 'titassportswear.appspot.com',
    iosBundleId: 'com.example.machineTrackerApp',
  );
}
